// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxhabiyrzbipdtvaosch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94aGFiaXlyemJpcGR0dmFvc2NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MDYxMTQsImV4cCI6MjA2ODM4MjExNH0.c4kzL8CnQZpQy-gXQNfgw0Rc2B01Jc7sPL5Zh7jfJhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});